changelog:
  exclude:
    labels:
      - ignore
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - breaking-change
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Refactoring
      labels:
        - refactor
        - refactoring
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"